Added cached auth tokens
artipie/cargo-adapter pull request #11
Opened 2021-12-14 07:48 UTC by olenagerasimova

Part of #7 
Added implementation of `AuthTokens` with guava evicted cache under the hood.

2021-12-14 08:13 UTC, genryxy requested changes
@olenagerasimova thanks, one minor comment

2021-12-14 08:13 UTC, genryxy commented on src/test/java/com/artipie/cargo/CachedAuthTokensTest.java
> + * @checkstyle MagicNumberCheck (500 lines)
since tag is incorrect

2021-12-14 08:13 UTC, genryxy commented on src/test/java/com/artipie/cargo/CachedAuthTokensTest.java
> +     * @checkstyle JavadocVariableCheck (500 lines)
and here

2021-12-14 09:06 UTC, genryxy approved these changes
@olenagerasimova thanks, looks good to me

2021-12-14 12:56 UTC, olenagerasimova commented
@g4s8 please, take a look/merge

2021-12-15 11:08 UTC, olenagerasimova commented
@g4s8 ping

2021-12-15 13:40 UTC, g4s8 commented
@olenagerasimova I granted you write permissions in this repo, please try to merge

2021-12-15 13:42 UTC, merged

2021-12-15 13:42 UTC, olenagerasimova commented
@g4s8 thanks, all good