Created `RsError` for error responses
artipie/cargo-adapter pull request #5
Opened 2021-11-30 09:41 UTC by olenagerasimova

Created `RsError` for error responses, added `PublishSlice` skeleton.

Note that in cargo it's recommended to return `OK` in case of error with errors description in json format.

2021-11-30 10:51 UTC, olenagerasimova commented
@g4s8 I'm planning to add IT in the next PR. This endpoint is described [here](https://doc.rust-lang.org/cargo/reference/registries.html#publish), as far as I understand, it will use [both protocols](https://doc.rust-lang.org/cargo/commands/cargo-publish.html), at first publish to git and then to the registry.

2021-11-30 11:48 UTC, genryxy commented on src/test/java/com/artipie/cargo/http/RsErrorTest.java
> +            )
the order of items in JSON is not determined

2021-11-30 11:48 UTC, genryxy requested changes
@olenagerasimova thanks, one question

2021-11-30 13:09 UTC, olenagerasimova commented
@genryxy thanks, used linked list

2021-11-30 13:28 UTC, genryxy approved these changes
@olenagerasimova thanks, looks good to me

2021-12-01 10:06 UTC, olenagerasimova commented
@g4s8 so, what do you say? Can we merge?

2021-12-02 05:01 UTC, olenagerasimova commented
@g4s8 ping

2021-12-02 12:59 UTC, olenagerasimova commented
@g4s8 ping

2021-12-08 16:39 UTC, g4s8 approved these changes
@olenagerasimova thanks

2021-12-08 16:39 UTC, merged